### ISSUE TITLE
商品の詳細ページも作る

### ISSUE THREAD

**Issue by qrg** [teori-katasoumoku/teori-katasoumoku.github.io#1]
luzlum 案の商品ページ内の項目リスト
- 商品名
- 商品写真
- 価格
- 購入できるページへのリンク
  - minne
  - BASE
- 商品説明
- 商品のサイズ
- 商品の重さ
- 素材
  - 綿100%か毛100%か綿と毛
- 染料
  - 植物染料か樹脂顔料
  - 自分で染めてない場合は表示しない
  - 植物染料なら茜など何で染めたか
- 使った技法
  - この中から1つ以上
    - 草木染め
    - 型染め
    - 手紡ぎ
    - 手織り(多綜絖卓上織機)
    - 手織り(クローズドリード卓上織機)
    - 手織り(腰機)
    - 手織り(ズームルーム)
- 取り扱いの注意点

**Comment by Luzlum** [comment]
ほぼこのサイトのように情報を整理したい
http://fab-fabric.com/store/fabric/105215928

**Comment by qrg** [comment]
hangout のチャットで **使った技法** の選択肢の相談ログ

> **Luz lum**
> このへんの選択肢にリンクを貼り、詳しいやり方の紹介ページに飛ばしたい

**Comment by qrg** [comment]
**素材** と **染料** の分類ももっときっちり分けることが必要だろうか

もし素材や染料がどういうものか紹介するページへのリンクとかアイコンを自動でつけたいなら、
より詳細な分類が必要

個人的にはそのほうがよりおもしろいサイトになり良さそうではと思う

**Comment by Luzlum** [comment]
- 素材
  1. 綿100%
  2. 綿100%(鳥取県産伯州綿を一部使用)
  3. 毛100%
  4. 綿x% 毛y%
  5. 綿x% 毛y%(鳥取県産伯州綿を一部使用)

というパターンがあるけど、4と5の場合、比率が商品ごとに異なる
だから、技法ほどはかっちり確定しないし、紹介ページもつくらない => 毎回手書き

**Comment by Luzlum** [comment]
追加
- 使った技法
  - この中から1つ以上
    - 草木染め
    - 型染め
    - 手紡ぎ
    - **裂織り**
    - 手織り(多綜絖卓上織機)
    - 手織り(クローズドリード卓上織機)
    - 手織り(腰機)
    - 手織り(ズームルーム)

**Comment by Luzlum** [comment]
- 染料
  - この中から1つ以上
    - 植物染料
    - 樹脂顔料
    - 手で染めておらず、市販の色糸または布のみを使用している

植物染料の種類は際限ないので、どんな植物で染めたかは商品説明に書いて、染料の項目分類は3つ(2つ?)がよさそうな気がしてきた。

染料の項目の目的は、洗濯の色落ち等のアテンション

**Comment by qrg** [comment]
染料の分類について

商品に使った植物染料の数はかなり限られていると思うので、
紹介ページはあとで足すということにしておきつつ
- 商品リスト
- 染料リスト

この両方を更新していくというのでも悪くない気がしてる

**Comment by Luzlum** [comment]
> 商品に使った植物染料の数はかなり限られていると思うので、
> 紹介ページはあとで足す

OK
植物染料リストって見たいもの？

**Comment by Luzlum** [comment]
染料の分類 からのリンク先は、
- 植物染料の特徴
- 樹脂顔料の特徴

で、内容が一般的な色落ちや変色の可能性とか洗濯方法の説明のページに飛ばすかなって考えてる
購入の注意点的な？ページ？

**Comment by qrg** [comment]
https://github.com/teori-katasoumoku/teori-katasoumoku.github.io/issues/1#issuecomment-235611193

見たいけど、そんな需要ないのかな
植物染料や染める技法は、ぐぐればすぐわかるものではあるんだけど

染料を煮込んだり実際に染めたりしてる写真があると「この布を作ってる人が実際に染料の材料を入手し抽出し染めている」というのが伝わって面白いと思って

もっと言うと、市販の機械で作った布製品との差別化はここにあるのではという気がしていて。

**Comment by Luzlum** [comment]
染め手としては、なにで染めれば何色になるのか知りたいので、需要ある。染め手でなくてもひとりでも見たい人がいるなら需要はある。よって需要ある。

インターネット上の有用な草木染め情報、ほとんどがアメブロなので、そうじゃないサイトがあってもいいなとは確かに思う。

**Comment by qrg** [comment]
そしたらこういうかんじかな
- 名前
- 写真
- 価格
- 購入できるページへのリンク
  - minne
  - BASE
- 説明
- 取り扱いの注意点
- サイズ
- 重さ
- 素材
- 染料
  - 植物染料 (植物の種類)
  - 樹脂顔料
  - 染めてない
- 技法
  - (1つ以上選択 複数可)
    - 草木染め
    - 型染め
    - 手紡ぎ
    - 手織り(多綜絖卓上織機)
    - 手織り(クローズドリード卓上織機)
    - 手織り(腰機)
    - 手織り(ズームルーム)

**Comment by Luzlum** [comment]
![2016-07-28 0 46 30](https://cloud.githubusercontent.com/assets/2553678/17181941/d33e249a-545c-11e6-95b2-b8ef277fc8c0.jpeg)

字が読みにくい

**Comment by qrg** [comment]
染料リストを更新してくれるなら

> 染料: **_植物染料 (茜)**_

みたいな自動で茜のページへのリンクにできるけど、どうだろ

**Comment by Luzlum** [comment]
https://minne.com/items/4402158

> [染料] 
> 茜、玉葱、人参、桜、柚子

今までの商品で最多の植物染料は5種類
おそらく平均して1商品に3種類くらいは使うから、表示方法考えないとウザそうではある
そこをクリアできそうなら染料リストにリンクするのいいと思う

**Comment by qrg** [comment]
> 染料:
> [茜] [玉葱] [人参] [桜] [柚子]

という雰囲気のタグみたいなの想像した

**Comment by Luzlum** [comment]
あっ いいですね

**Comment by qrg** [comment]
👍

**Comment by Luzlum** [comment]
商品情報の書き方、とりあえずmarkdownで書いてるんだけど、こういう感じで整形に不都合あるかな

``` markdown
# products Data

## 草木染め綿の手織り布
### productname
草木染め綿の手織り布

### imgfile

### price
15,000円

### links to buy
#### minne
https://minne.com/items/5293812

#### BASE


### explanation
首まわりにさらっと巻ける、夏にも使える布を織りました。
さらさらとした風合いでハリがありながら、くったりとしたやわらかさがあります。
身につける用途以外にも、テーブルセンターなどとして使うのも良いかもしれません。

桜で染めた糸を3色と、葛で染めた緑の糸を使用しています。

### attention
ドライクリーニングをおすすめします。
手洗いをする際は、色落ちや縮みを減らすために、ぬるま湯でやさしく洗ってください。洗剤を使う場合は中性洗剤を使ってください。
保管するときは色あせを進ませないために直射日光を避けてください。

手織り製品のため、ゆがみ等があります。
また、天然染料を使っているので、制作条件や使用環境によっては色褪せや変色の可能性が化学染料よりも高いです。大事にしまっておくのではなく、変化を怖がらずにどんどん使ってもらうのがいちばんいいと思います。

### size
約20cmx185cm

### weight
約60g

### material
綿100%

### dye
植物染料

- 桜
- 葛

### technique
- 草木染め
- 手織り(クローズドリード卓上織機)
```

**Comment by qrg** [comment]
なんとでもなりそうだけど、 yaml でおおざっぱにフォーマット作ってみた
これでどうだろう

``` yaml
-
  name: 草木染め綿の手織り布
  image: null
  price: 15000
  links_to_buy:
    -
      label: minnne
      uri: https://minne.com/items/5293812
  description: |
    首まわりにさらっと巻ける、夏にも使える布を織りました。
    さらさらとした風合いでハリがありながら、くったりとしたやわらかさがあります。
    身につける用途以外にも、テーブルセンターなどとして使うのも良いかもしれません。

    桜で染めた糸を3色と、葛で染めた緑の糸を使用しています。
  usage_note: |
    ドライクリーニングをおすすめします。
    手洗いをする際は、色落ちや縮みを減らすために、ぬるま湯でやさしく洗ってください。洗剤を使う場合は中性洗剤を使ってください。
    保管するときは色あせを進ませないために直射日光を避けてください。

    手織り製品のため、ゆがみ等があります。
    また、天然染料を使っているので、制作条件や使用環境によっては色褪せや変色の可能性が化学染料よりも高いです。大事にしまっておくのではなく、変化を怖がらずにどんどん使ってもらうのがいちばんいいと思います。
  size:
    height: 200
    width: 1850
    thickness: null
  weight: 60
  materials:
    - 綿 100 %
  dye:
    type: 植物染料
    materials:
      - 桜
      - 葛
  methods:
    - 草木染め
    - 手織り (クローズドリード卓上織機)

-
  name: 他の布
  image: null
  price: ...

```

**Comment by qrg** [comment]
yaml 初ならここで試すと便利
[YAML parser for JavaScript - JS-YAML](http://nodeca.github.io/js-yaml/#yaml=LQogIG5hbWU6IOiNieacqOafk+OCgee2v+OBruaJi+e5lOOCiuW4gwogIGltYWdlOiBudWxsCiAgcHJpY2U6IDE1MDAwCiAgbGlua3NfdG9fYnV5OgogICAgLQogICAgICBsYWJlbDogbWlubm5lCiAgICAgIHVyaTogaHR0cHM6Ly9taW5uZS5jb20vaXRlbXMvNTI5MzgxMgogIGRlc2NyaXB0aW9uOiB8CiAgICDpppbjgb7jgo/jgorjgavjgZXjgonjgaPjgajlt7vjgZHjgovjgIHlpI/jgavjgoLkvb/jgYjjgovluIPjgpLnuZTjgorjgb7jgZfjgZ/jgIIKICAgIOOBleOCieOBleOCieOBqOOBl+OBn+miqOWQiOOBhOOBp+ODj+ODquOBjOOBguOCiuOBquOBjOOCieOAgeOBj+OBo+OBn+OCiuOBqOOBl+OBn+OChOOCj+OCieOBi+OBleOBjOOBguOCiuOBvuOBmeOAggogICAg6Lqr44Gr44Gk44GR44KL55So6YCU5Lul5aSW44Gr44KC44CB44OG44O844OW44Or44K744Oz44K/44O844Gq44Gp44Go44GX44Gm5L2/44GG44Gu44KC6Imv44GE44GL44KC44GX44KM44G+44Gb44KT44CCCgogICAg5qGc44Gn5p+T44KB44Gf57O444KSM+iJsuOBqOOAgeiRm+OBp+afk+OCgeOBn+e3keOBruezuOOCkuS9v+eUqOOBl+OBpuOBhOOBvuOBmeOAggogIHVzYWdlX25vdGU6IHwKICAgIOODieODqeOCpOOCr+ODquODvOODi+ODs+OCsOOCkuOBiuOBmeOBmeOCgeOBl+OBvuOBmeOAggogICAg5omL5rSX44GE44KS44GZ44KL6Zqb44Gv44CB6Imy6JC944Gh44KE57iu44G/44KS5rib44KJ44GZ44Gf44KB44Gr44CB44Gs44KL44G+5rmv44Gn44KE44GV44GX44GP5rSX44Gj44Gm44GP44Gg44GV44GE44CC5rSX5Ymk44KS5L2/44GG5aC05ZCI44Gv5Lit5oCn5rSX5Ymk44KS5L2/44Gj44Gm44GP44Gg44GV44GE44CCCiAgICDkv53nrqHjgZnjgovjgajjgY3jga/oibLjgYLjgZvjgpLpgLLjgb7jgZvjgarjgYTjgZ/jgoHjgavnm7TlsITml6XlhYnjgpLpgb/jgZHjgabjgY/jgaDjgZXjgYTjgIIKCiAgICDmiYvnuZTjgoroo73lk4Hjga7jgZ/jgoHjgIHjgobjgYzjgb/nrYnjgYzjgYLjgorjgb7jgZnjgIIKICAgIOOBvuOBn+OAgeWkqeeEtuafk+aWmeOCkuS9v+OBo+OBpuOBhOOCi+OBruOBp+OAgeWItuS9nOadoeS7tuOChOS9v+eUqOeSsOWig+OBq+OCiOOBo+OBpuOBr+iJsuikquOBm+OChOWkieiJsuOBruWPr+iDveaAp+OBjOWMluWtpuafk+aWmeOCiOOCiuOCgumrmOOBhOOBp+OBmeOAguWkp+S6i+OBq+OBl+OBvuOBo+OBpuOBiuOBj+OBruOBp+OBr+OBquOBj+OAgeWkieWMluOCkuaAluOBjOOCieOBmuOBq+OBqeOCk+OBqeOCk+S9v+OBo+OBpuOCguOCieOBhuOBruOBjOOBhOOBoeOBsOOCk+OBhOOBhOOBqOaAneOBhOOBvuOBmeOAggogIHNpemU6CiAgICBoZWlnaHQ6IDIwMAogICAgd2lkdGg6IDE4NTAKICAgIHRoaWNrbmVzczogbnVsbAogIHdlaWdodDogNjAKICBtYXRlcmlhbHM6CiAgICAtIOe2vyAxMDAgJQogIGR5ZToKICAgIHR5cGU6IOakjeeJqeafk+aWmQogICAgbWF0ZXJpYWxzOgogICAgICAtIOahnAogICAgICAtIOiRmwogIG1ldGhvZHM6CiAgICAtIOiNieacqOafk+OCgQogICAgLSDmiYvnuZTjgoogKOOCr+ODreODvOOCuuODieODquODvOODieWNk+S4iue5lOapnykKCi0KICBuYW1lOiDku5bjga7luIMKICBpbWFnZTogbnVsbAogIHByaWNlOiAuLi4K)

**Comment by qrg** [comment]
全 products を配列にして全部1ファイルにまとめるか、 
product 別にファイル分けるかどうしようかな

長くなりそうだからファイルを個別に分ける方向で始めてみることにする

**Comment by qrg** [comment]
いまさら気づいたけど、 `id` が必要
id はファイル名になり、結果的に URI の一部になるため、ユニークなものである必要がある

id の命名規則を決めるとしたら何がいいだろうか
商品名の英語名あたりだろうか

Luzlum はドイツ語のほうが得意なのでそれでも良いけども、
英語か日本語のほうが検索インデックス時に意味を理解してもらいやすそうではある(ただし雑な予想)

fab-fabric のように機械的な id を振ってしまうのも手だけど、手動で機械的な id をyml に書くのはわかりづらいだけなので、今回は選択肢から外して良さそう
http://fab-fabric.com/store/fabric/105215928

なにかもっと便利な案あるかな

**Comment by qrg** [comment]
`id: kusaki-zome-men-no-teori-nuno`

ゾメメン のところ気になる

**Comment by qrg** [comment]
ゾメメン

**Comment by Luzlum** [comment]
id
どれもこれも同じような商品名になりがちなため、商品名をそのまますると、同じid発生すると思うし、商品名にした割に見分けつかない可能性出てくるんだよな〜

なので、作成年月日や、草木染めor not、布or not等を記号番号にする、とかかなあって思うんだけど、どう

**Comment by qrg** [comment]
良さそうに思える
例が欲しい

**Comment by Luzlum** [comment]
草木染め綿の手織り布 http://minne.com/items/5293812
これだと、例えば
tbawfpft160701

形状が布:t (Tuch 布) <=> 形状が布でない:n(nähend 縫われている)
素材が綿:ba(Baumwolle 綿) /素材が羊毛:wo(Wolle 羊毛)/素材が綿と羊毛:bw
手織りのみ:we(weben 織る)/手染めのみ:fa(färben 染める)/手織りと手染め:wf
植物染料:pf(Pflanze 植物) /樹脂顔料:pi(Pigment 顔料)/植物染料と樹脂顔料:pp/染めてない:ro(roh 生の)
+
製作者記号1文字
+
西暦下2桁
+
月2桁
+
その月の何個目の製品か2桁

みたいな感じかなあ…
tbawfpftが大多数になりそうではある

**Comment by Luzlum** [comment]
メリットとして、URIを見たときに洗濯の仕方がわかる

**Comment by Luzlum** [comment]
ただし私に限る

**Comment by qrg** [comment]
そのルールだと、記号化したあとの文字数が 1-2文字とぶれがあるため、
`t-ba-wf-pf-t-1607-01` のようにセパレーターを入れてあげるといいかもしれない。

でなければ文字の並びによっては判別ができなくなるケースが発生する可能性がある。

あとファイル名にして並べたとき、文字列の頭からソートの評価されていくため、
ファイル名ソートしたときのソート基準にしたい優先順位の順にすると多少便利になりそう

**Comment by qrg** [comment]
あと別案になってしまうけど、
商品名が商品の説明になっているためにかぶりやすくなっているということだと思うので、
全て命名するという手もありそう

ただしこの案は名前を思いつかないと辛い
愛着は湧きそう

### 例1.

太陽 (solar) の自然光によって生まれる色に近づけ、長時間見ても疲れにくいというコンセプトの落ち着いたカラースキーム

→ 命名 **Solarized**

### 例2.

唐物茄子茶入

原産地: 唐
技法: 漆繕い
形状: 茄子型
用途: 茶入

→ 命名: **九十九茄子**

**Comment by qrg** [comment]
作ったものに名前をつけるの、愛着湧いて楽しいし、買う側も覚えやすく呼びやすいというメリットあるため、個人的にはどちらかというと逐一命名案のほうが好きかな

せっかくハンドメイドで工業製品とは違う良さがあるのに、名前が工業製品ぽくなってしまうのが惜しいというのもある

**Comment by qrg** [comment]
id は id で買う側は普通は見ない識別子ってことで、命名は `name` でやればというのが正しい気もしてきた

**Comment by Luzlum** [comment]
別案、センスが超必要ではあるものの、たしかにまあたしかに

「星と爆薬のマリアージュ」みたいなのは全く許せないが、「カナダの象」ならまあまあ許容でき、「渋柿」は抵抗なく、「夜明け」だとやや厳しい、「茜綾縞布」ぐらいが楽だけど完全に説明文、というように、かなり悩みそう
でも命名はするべきな気がする

**Comment by qrg** [comment]
> 茜綾縞布

よみかたがわからなかった

**Comment by Luzlum** [comment]
織物の命名？は 茜綾縞布 みたいなのが割と多くて、読み方は訓読みで良いんじゃないかと思う。
あかねあやしまぬの、または、あかねあやしまふ、みたいな。
茜を使った綾織の縞模様の布なんですねって感じ。命名兼分類っぽい。

**Comment by qrg** [comment]
id のほうの話に戻すと、
- ドイツ語で大丈夫そうか
  - ドイツ語の範疇は基本的には Luzlum しか触れなさそう
  - 分類が関わる他の機能を作るとき、そちらもドイツ語にするかどうか逐一考えることにもなる
  - (ただしまだ予定にもない機能についての懸念なので考える必要あまりないと切ることもできる)
- 形状-素材-技法-染料-作者-日付-番号 の順番で良さそうかどうか
  - 並んだときぱっとみて一番便利そうな順番にする
  - もしくは順番が覚えやすい順番にする

このへんどうだろう

**Comment by qrg** [comment]
あー、あと絶対に二度は同じ命名はしないぜという気持ちで `akane-aya-shima-nuno` とかにする案も一応ある

**Comment by Luzlum** [comment]
### 言語

英語の方が扱いやすい人間が多いため、英語にすべき

### idの中身の順
- 普段会話中に実物を特定する時の条件の絞り方は、作者->形状->素材->技法->染料->色(色数がまちまちなので色は記号化しにくそう)
- 買う人にはどうでもいいけど、あると管理等に便利な情報は、作者と織機の種類(織機の名前長すぎるので推測できる程度に記号化するのは難しそう)
- IDに含めると便利になる情報があんまり思いつかない、ID名作成がしやすいかどうか=実物を思い浮かべたら自然と作成できるかどうか、が大事な気がする。そういう意味では、会話で実物を特定する条件の絞り方(作者->形状->素材->技法->染料->色)かな

**Comment by qrg** [comment]
とりあえず英語版案
dye が2カ所にある
- 形状
  - CL 布 **cl**oth
  - SW 縫 **s**e**w**
- 素材
  - CO 綿 **co**tton
  - WO 羊毛 **wo**ol
  - CW 綿/羊毛
- 技法
  - WV 手織り **w**ea**v**e
  - DY 手染め **dy**e
  - WD 手織り/手染め
- 染料
  - DY 植物染料 **dy**e (染料)
  - PG 樹脂顔料 **p**i**g**ment (顔料)
  - DP 植物染料/樹脂顔料
  - UD 染めてない  **u**n**d**yed

これだけだと、「縫製して」「綿/羊毛使って」「手織り/手染めして」「植物染料使用の」ぜんぜん別の製品をふつうに作ると思うので、ユニークにならなさそうで、
日付日時つける以外になにかないかなーと考えている

ほか
- 分類はこれ以外に増えるケースがどの程度考えられるか
  - 大分類と小分類どちらも

が気になっている

**Comment by qrg** [comment]
画像は複数あると思うので、複数形に変更する必要がありそう

id を入れるとこのような感じに
ただし id については https://github.com/teori-katasoumoku/teori-katasoumoku.github.io/issues/1#issuecomment-238092085 の内容をまだ考える必要ある

**追記**
- `dye` をフラットな構造にして `dye_type` と `dye_materials` にした
- `size` の中身もフラットな構造にした

``` yml
id: kusaki-zome-men-no-teori-nuno
name: 草木染め綿の手織り布
images:
  - /images/products/kusaki-zome-men-no-teori-nuno.jpg
  - /images/products/kusaki-zome-men-no-teori-nuno-detail-1.jpg
  - /images/products/kusaki-zome-men-no-teori-nuno-detail-2.jpg
  - /images/products/kusaki-zome-men-no-teori-nuno-usage.jpg
price: 15000
links_to_buy:
  -
    label: minnne
    uri: https://minne.com/items/5293812
description: |
  首まわりにさらっと巻ける、夏にも使える布を織りました。
  さらさらとした風合いでハリがありながら、くったりとしたやわらかさがあります。
  身につける用途以外にも、テーブルセンターなどとして使うのも良いかもしれません。

  桜で染めた糸を3色と、葛で染めた緑の糸を使用しています。
usage_note: |
  ドライクリーニングをおすすめします。
  手洗いをする際は、色落ちや縮みを減らすために、ぬるま湯でやさしく洗ってください。洗剤を使う場合は中性洗剤を使ってください。
  保管するときは色あせを進ませないために直射日光を避けてください。

  手織り製品のため、ゆがみ等があります。
  また、天然染料を使っているので、制作条件や使用環境によっては色褪せや変色の可能性が化学染料よりも高いです。大事にしまっておくのではなく、変化を怖がらずにどんどん使ってもらうのがいちばんいいと思います。
height: 200
width: 1850
thickness: null
weight: 60
materials:
  - 綿 100 %
dye_type: 植物染料
dye_materials:
  - 桜
  - 葛
methods:
```
